services:
  traefik:
    image: "traefik:v3.1"
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=ragapp-network
      # Default username: admin, password: admin
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME:-admin}:${HASHED_PASSWORD:-$$apr1$$3gG256rA$$BomHrC/uMhL807k/t7Wd6/}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api
    networks:
      - ragapp-network

  ragapp-cs50:
    build: ../..
    image: ragapp/ragapp:latest
    volumes:
      - ./data/cs50-data:/app/data
    labels:
      - ragapp.app_name=cs50
      - traefik.enable=true
      - traefik.http.services.ragapp-cs50.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs50.rule=PathPrefix(`/a/cs50`)
      - traefik.http.routers.ragapp-cs50-admin.rule=PathRegexp(`/a/cs50/admin`)
      - traefik.http.routers.ragapp-cs50-admin.middlewares=admin-auth
    environment:
      - BASE_URL=/a/cs50
      - FILESERVER_URL_PREFIX=/a/cs50/api/files
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_DIM=1024
    networks:
      - ragapp-network

  ragapp-cs101:
    build: ../..
    image: ragapp/ragapp:latest
    volumes:
      - ./data/cs101-data:/app/data
    labels:
      - ragapp.app_name=cs101
      - traefik.enable=true
      - traefik.http.services.ragapp-cs101.loadbalancer.server.port=8000
      - traefik.http.routers.ragapp-cs101.rule=PathPrefix(`/a/cs101`)
      - traefik.http.routers.ragapp-cs101-admin.rule=PathRegexp(`/a/cs101/admin`)
      - traefik.http.routers.ragapp-cs101-admin.middlewares=admin-auth
    environment:
      - BASE_URL=/a/cs101
      - FILESERVER_URL_PREFIX=/a/cs101/api/files
      - MODEL_PROVIDER=openai
      - MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - EMBEDDING_DIM=1024
    networks:
      - ragapp-network
  
  manager:
    image: ragapp/manager:latest
    build: ../../src/manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BASE_URL=/manager
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.admin-manager.rule=PathPrefix(`/manager`)
      - traefik.http.middlewares.strip-manager-path.stripprefix.prefixes=/manager
      - traefik.http.routers.admin-manager.middlewares=strip-manager-path,admin-auth
    networks:
      - ragapp-network
  
networks:
  ragapp-network:
    name: ragapp-network
