name: Manager - Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - 'src/manager/**'

jobs:
  release_tagged_image:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - <<: *checkout_code
      - <<: *setup_buildx
      - <<: *login_docker_hub

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src/manager
          file: ./src/manager/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ragapp/manager:${{ steps.tag.outputs.TAG }}
            ragapp/manager:latest

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "README.md"
          name: Release ${{ steps.tag.outputs.TAG }}
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}

  release_dev_image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - <<: *checkout_code
      - <<: *setup_buildx
      - <<: *login_docker_hub

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/manager
          file: ./src/manager/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/${{ github.repository }}:latest


# Common steps
steps:
  checkout_code: &checkout_code
    - name: Check out the code
      uses: actions/checkout@v2

  setup_buildx: &setup_buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

  login_docker_hub: &login_docker_hub
    - name: Log in to Docker Hub Container Registry
      uses: docker/login-action@v3
      with:
        username: marcusschiesser
        password: ${{ secrets.DOCKER_TOKEN }}
